### PR TITLE
Update some minor typos and grammatical issues

### PR DESCRIPTION
**Pull request by jcolag**
I'm a few years late to the book, but I started reviewing Free Culture properties for my blog. While I was reading through, I've been writing Markdown enough that I reflexively did some minor proofreading as I went.  Hopefully, I didn't accidentally step on any dialect differences.  The word "truckie" suggests Australian English and I haven't read _nearly_ enough Australian content to get a sense of the common differences...

### CODE REVIEW

**Comment by shakna-israel** [comment]
There's a _lot_ of work in here.

I have noticed one or two changes I wouldn't have made, but as I'm completely embarrassed by the writing quality of Drakes compared to my writing today, it might take me a little while to work through this.

Um. As an example of a chance I wouldn't have made, you changed "Intelligence Quiz" to "Intelligence Quotient". The original sentence is plainly bad as-is, and the change would reflect Suzie's way of thinking, but it actually breaks the sentence with the change.

This is your change:

> Her IQ ranked her as the smartest person alive, clocking in at 268, however she didn’t believe it, said experience meant more than any potential an Intelligence Quotient set her at.

An IQ isn't a verb here, it can't set you at anything. So a better sentence might be:

> Her IQ ranked her as the smartest person alive, clocking in at 268, however she didn’t believe it, said experience meant more than any potential Intelligence Quotient.

---

Like I said before though - there is a _huge_ amount of work that has gone into the patch. Fixing up your/you're alone would have taken a while, especially as I was terrible at that eight years ago.

I do intend to read through and merge changes, but reading my old writing does make me want to rewrite the whole thing. It's awful. My writing, that is. Your patch is great!

**Comment by shakna-israel** [comment]
Well, it's done. I'm very very tempted to rewrite it, because I hate it, but it's done.

Couple small things of note:

+ Suzie, though a poorly written character, was absolutely meant to be a PTSD driven character. PTSD & arrogance are her two defining traits, and what causes her ability to act erratically.

+ I never intended to imply that the main bad guy is killed off. They aren't, and are back in the sequel. Which I expect is just as horrible as this was, considering I wrote them three months apart for some writing competition.

+ I actually have a number of open books. Some, like this, I'm embarrassed by. Others less so. [Necromancer's Apprentice](https://github.com/shakna-israel/NecromancersApprentice) is a little better, and under the same license.

**Comment by jcolag** [comment]
For what it's worth, there's a _lot_ to like in the book and I'll (eventually) look at the sequels.  I definitely wouldn't have filed the pull request if I didn't think it was going to help anything.  Wherever it goes, keep in touch!

**Comment by shakna-israel** [comment]
It certainly presents a world with potential. I'd love to see what someone else could do with it, as I probably won't be getting around to a better rewrite any time soon.

And thanks again for your efforts. It does help.

**Pull request merged**
